### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by gixtuh** [UselessPrograms/py-webdriver-torso#9]
when i run  WEBDRIVER.py, i get:
/home/[ __ ]/.local/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
REMOVED OLD FILES
Traceback (most recent call last):
  File "/home/streamk878/python/projects/py-webdriver-torso-master/WEBDRIVER/WEBDRIVER.py", line 100, in <module>
    img1.rectangle(shapeB, fill="blue", outline="blue")
  File "/home/streamk878/.local/lib/python3.9/site-packages/PIL/ImageDraw.py", line 292, in rectangle
    self.draw.draw_rectangle(xy, fill, 1)
ValueError: y1 must be greater than or equal to y0

what i missed?

**Comment by gixtuh** [comment]
oops, i just installed newer version of Pillow, not 9.0.0
